name: 🚥 Status Checks
on:
  push:
    tags:
      - 'v*' # Only runs if pushing a tag

jobs:
  tests:
    name: 👀 Evaluate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Don't cancel other OS runners if one fails.
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # Runs only on Linux, still cross-compiles all builds
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - uses: actions/checkout@v4
        name: 🧾 Checkout

      - uses: chickensoft-games/setup-godot@v2
        name: 🤖 Setup Godot
        with:
          version: 4.7.2
          use-dotnet: false
          # Include the Godot Export Templates (the default is false).
          include-templates: true

      - name: 🔬 Verify Setup
        run: |
          godot --version

      - name: Export Game Executables
        run: |
          mkdir -p build/windows build/linux build/mac build/web

          godot --headless --export-release "Windows Desktop" build/windows/game.exe
          godot --headless --export-release "Linux x86_64" build/linux/game.x86_64
          godot --headless --export-release "macOS" build/mac/game.zip
          godot --headless --export-release "Web" build/web/index.html

      - name: Archive and build packages
        run: |
          cd build/web && zip -r ../../web-build.zip . && cd ../..
          cd build/linux && zip -r ../../linux-build.zip . && cd ../..
          mv build/windows/game.exe ./windows-build.exe
          mv build/mac/game.zip ./mac-build.zip

      - name: Publish to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-build.exe
            linux-build.zip
            mac-build.zip
            web-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      # Do whatever you want!
